import express from "express";
import path from "path";
import dotenv from "dotenv";
import { createServer as createViteServer } from "vite";
import { GoogleGenAI } from "@google/genai";

dotenv.config();

const app = express();
app.use(express.json());

const PORT = 3000;

// Lazy client setup to prevent crashing if GEMINI_API_KEY is undefined on startup
let aiInstance: any = null;

function getGeminiClient() {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    return null; // Return null so we can return a friendly, realistic mock response instead of crashing
  }
  if (!aiInstance) {
    aiInstance = new GoogleGenAI({
      apiKey: apiKey,
      httpOptions: {
        headers: {
          'User-Agent': 'aistudio-build',
        }
      }
    });
  }
  return aiInstance;
}

// 1. Live AI Param Decryptor Analysis Endpoint
app.post("/api/gemini/analyze", async (req, res) => {
  try {
    const { reportText, source } = req.body;

    const prompt = `You are a clinical cardiovascular education assistant.
Your goal is to parse and decrypt dense, complex cardiological reports, clinical metrics, laboratory parameters (such as Ejection Fraction - EF, arterial blockages, arterial plaque, or ischemic ECG deviations), and translate them into a simplified, clear, easy-to-understand educational summary.

Here is the healthcare record / parameters to analyze:
Source / Type: ${source || "Medical Report"}
Content:
${reportText}

Provide your analysis in English.
Ensure your response is divided into these structural sections:
1. **Summary**: A reassuring, clear high-level translation of what the report means in simple terms.
2. **Key Parameters Explained**: Breakdown of complex metrics found (such as what Ejection Fraction (EF) at this value means, or what LAD blockage means).
3. **Critical Differentiations**: State if the findings align closer with Heart Attack (circulation blockage), Cardiac Arrest (sudden electrical heart stoppage), or Heart Failure (chronic weak pump), or if it is a general clinical finding.
4. **Questions for your Physician**: 3-4 precise questions the patient can bring to their physical examination.

Keep the language Empathetic, Clear, and strictly educational. Avoid creating simulated medical diagnostics.`;

    const ai = getGeminiClient();
    if (!ai) {
      // Graceful clinical mock callback when key is missing, so user doesn't get a crashed dev experience
      console.warn("GEMINI_API_KEY missing - returning simulated high-fidelity clinic-themed offline evaluation response.");
      const mockResultEn = `### **Parser Status:** _Offline Education Blueprint Response_
      
### **1. Summary**
The record represents a detailed cardiology reading. In direct, everyday language: There is a noted reduction in the heart's pumping efficiency, accompanied by localized arterial blockages in the primary coronary vessels. The principal plumbing is partially compressed, restricting blood and oxygen replenishment to the heart muscle.

### **2. Key Parameters Explained**
*   **Ejection Fraction (EF) ~ 35%**: A healthy heart operates at an EF of 55% to 70%. An EF of 35% indicates moderate mechanical exhaustion or "Pump Fatigue". The heart muscle remains intact but is pumping out less blood with each contraction.
*   **LAD Artery Stenosis ~ 85%**: The Left Anterior Descending (LAD) artery is often called the "primary pump pipe". An 85% blockage represents a significant plumbing constraint, starving the front wall of the heart of optimal circulatory volume.
*   **Ischemic ST changes on ECG**: This indicates minor current stress or oxygen starvation of the muscle cells under cardiac workload.

### **3. Critical Differentiations**
*   **Heart Attack Risk (Plumbing)**: **HIGH**. The 85% stenosis in the LAD vessel is an active circulation hazard that can escalate into a complete heart attack if a blood clot closes the gap.
*   **Heart Failure Markers (Mechanical)**: **ACTIVE**. The EF of 35% represents active Congestive Heart Failure symptoms (tiredness, mechanical weakness).
*   **Cardiac Arrest Risk (Electrical)**: **MODERATE**. While no active electrical ventricular fiber spasms are recorded, mechanical distress increases electrical instability.

### **4. Recommended Questions for your Physician**
1. "Given my EF is 35%, would you suggest beginning beta-blockers or liquid-relievers to support my pump workload?"
2. "Should we schedule an angiogram or stress study to assess the 85% LAD plumbing stenosis?"
3. "What signs of fluid congestion (like ankle swelling) should I watch for daily at home?"`;

      return res.json({ text: mockResultEn, isMock: true });
    }

    const response = await ai.models.generateContent({
      model: "gemini-3.5-flash",
      contents: prompt,
    });

    res.json({ text: response.text || "No response generated by model.", isMock: false });
  } catch (error: any) {
    console.error("Gemini Analyze Error:", error);
    res.status(500).json({ error: error.message || "Internal server error" });
  }
});

// 2. Live Interactive Follow-Up Chat Endpoint
app.post("/api/gemini/chat", async (req, res) => {
  try {
    const { messages } = req.body;

    const systemInstruction = `You are a clinical cardiovascular education chatbot.
You are helping the patient/user answer follow-up questions about their cardiological parameters, symptoms, ECG records, or cardiac wellness guidelines.
IMPORTANT: You are an educator, not a direct emergency provider. Always recommend calling localized medical hotlines (112, 108 in India, or 911) if they are experiencing radiating chest pressure, breathlessness, or cold sweats right now.
Respond in English. Keep answers structured, highly readable, reassuring, and concise. Use bullet points for clarity.`;

    const ai = getGeminiClient();
    if (!ai) {
      // Realistic offline conversational answers depending on user's query keywords
      const lastUserMsg = messages[messages.length - 1]?.text?.toLowerCase() || "";
      let reply = "";
      if (lastUserMsg.includes("ef") || lastUserMsg.includes("ejection")) {
        reply = `### Educational Guidance on Ejection Fraction (EF):\n\n*   **What is EF?**: Ejection Fraction is the measurement of how much blood the left ventricle pumps out with each contraction.\n*   **Ranges**: Normal is 55%-70%. Under 40% designates structural weakness, often classified as congestive heart failure.\n*   **Therapies**: Restorative medications (beta-blockers, ACE inhibitors, SGLT2 inhibitors) are typically advised by cardiologists to reduce pumping resistance.`;
      } else if (lastUserMsg.includes("cpr") || lastUserMsg.includes("arrest")) {
        reply = `### Cardiac Arrest & CPR Lifeline Facts:\n\n*   **Cardiac Arrest**: An electrical failure causing heart rhythm to stop entirely. Immediate action is critical.\n*   **Response**: Dial **112** (All-India Emergency) or **108** (Ambulance) instantly!\n*   **CPR Rhythm**: Push hard and fast in the center of the chest at 100–120 compressions per minute to manually preserve blood flow to the brain as medical dispatch arrives.`;
      } else {
        reply = `### Sajivani Clinical Wellness Note:\n\n*   **Diagnostic Integrity**: Cardiological records require evaluation alongside clinical examinations by an active medical practitioner.\n*   **Critical Action**: If you or someone nearby is experiencing active radiating pain, cold sweats, or breathing struggles, do not wait—please call Indian emergency dispatches **108** or **112** immediately.`;
      }
      return res.json({ text: reply, isMock: true });
    }

    // Prepare contents array matching the @google/genai format
    const contents = messages.map((m: any) => ({
      role: m.sender === "user" ? "user" : "model",
      parts: [{ text: m.text }]
    }));

    const response = await ai.models.generateContent({
      model: "gemini-3.5-flash",
      contents: contents,
      config: {
        systemInstruction: systemInstruction,
      }
    });

    res.json({ text: response.text || "No response generated by model.", isMock: false });
  } catch (error: any) {
    console.error("Gemini Chat Error:", error);
    res.status(500).json({ error: error.message || "Internal server error" });
  }
});

// 3. Vite development vs static production serve setup
const buildPath = path.join(process.cwd(), "dist");

if (process.env.NODE_ENV !== "production") {
  const startVite = async () => {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);

    app.listen(PORT, "0.0.0.0", () => {
      console.log(`[Development Mode] Full-stack Server running at http://0.0.0.0:${PORT}`);
    });
  };
  startVite();
} else {
  app.use(express.static(buildPath));
  app.get("*", (req, res) => {
    res.sendFile(path.join(buildPath, "index.html"));
  });

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`[Production Mode] Full-stack Server running on port ${PORT}`);
  });
}
